name: logicapp infra

on:
  push:main
  pull_request:

jobs:
  create-logicapp-infra:
    env:
      AZURE_LOGICAPP_PACKAGE_PATH: .
      DEPLOY_ENV: ${{ matrix.azureenv }}
      DOTNET_VERSION: 3.1.301
      RG_CON: GHConnections
      RG_LA: GHApp
    environment: sandbox
    name: Create logicapp infra
    runs-on: ubuntu-latest
    steps:
    - name: Set the env variables according to env
      run: 'echo ${{matrix.azureenv}}

        echo $DEPLOY_ENV

        echo "AZURE_APP_ENV_NAME=${AZURE_APP_NAME}${DEPLOY_ENV}" >> $GITHUB_ENV

        '
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Logic App
      run: 'az extension add --name logic

        az config set extension.use_dynamic_install=yes_without_prompt

        az logic workflow create --name "testLogicApp" \

        --resource-group "rg-by-workflow-shared-dev-eus2-01" \

        --location "eastus2" \

        --definition "testDefinition.json"'
    strategy:
      matrix:
        azureenv:
        - sandbox
